on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to update Notion
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notion Update
        uses: ./
        env:
          NOTION_BOT_SECRET_KEY: ${{ secrets.NOTION_BOT_SECRET_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          status-property: "Status"
          pr-property: "PR Link"

          draft: "In progress"
          merged: "Done"

          opened: "In progress"
          ready_for_review: "In review"
          closed: "Done"
